CREATE DATABASE IF NOT EXISTS country_data;
USE country_data;

-- SECURITY --
DROP TABLE IF EXISTS INTERNATIONAL_DATA;
DROP TABLE IF EXISTS INCOME_BY_COUNTRY;
DROP TABLE IF EXISTS COUNTRY;

-- TABLE COUNTRY --
-- countries.csv and country_names_area.csv --

CREATE TABLE COUNTRY (
	COUNTRY_ID INTEGER NOT NULL,
	ISO VARCHAR(2),
	ISO3 VARCHAR(3),
	FIPS VARCHAR(2),
	DISPLAY_NAME VARCHAR(20),
	OFFICIAL_NAME VARCHAR(20),
	CAPITAL VARCHAR(20),
	COUNTRY_AREA FLOAT(2),
	CONTINENT VARCHAR(20),
	CURRENCY_CODE VARCHAR(3),
	CURRENCY_NAME VARCHAR(20),
	PHONE INTEGER,
	REGION_CODE INTEGER,
	REGION_NAME VARCHAR(20),
	SUBREGION_CODE INTEGER,
	SUBREGION_NAME VARCHAR(20),
	INTERMEDIATE_REGION_CODE INTEGER,
	INTERMEDIATE_REGION_NAME VARCHAR(20),
	C_STATUS VARCHAR(20),
	DEVELOPMENT VARCHAR(20),
	SIDS BOOLEAN,	-- SMALL ISLAND DEVELOPING STATES
	LLDC BOOLEAN,	-- LAND LOCKED DEVELOPING COUNTRIES
	LDC BOOLEAN,	-- LEAST DEVELOPED COUNTRIES
	AREA_SQKM INTEGER,
	POPULATION INTEGER,
	PRIMARY KEY(COUNTRY_ID)
);

-- TABLE INTERNATIONAL_DATA --
-- !!!!!!!!! MIDYEAR_POPULATION_5YR_AGE_SEX --

CREATE TABLE INTERNATIONAL_DATA(

	-- COMMON FOR EVERY FILE --
	D_COUNTRY_ID INTEGER NOT NULL,
	D_YEAR INTEGER NOT NULL,
	COUNTRY_NAME VARCHAR(20),

	-- AGE_SPECIFIC_FERTILITY_RATES --
	FERTILITY_RATE_15_19 FLOAT(1),
	FERTILITY_RATE_20_24 FLOAT(1),
	FERTILITY_RATE_25_29 FLOAT(1),
	FERTILITY_RATE_30_34 FLOAT(1),
	FERTILITY_RATE_35_39 FLOAT(1),
	FERTILITY_RATE_40_44 FLOAT(1),
	FERTILITY_RATE_45_49 FLOAT(1),
	TOTAL_FERTILITY_RATE FLOAT(4),
	GROSS_REPRODUCTION_RATE FLOAT(4),
	SEX_RATIO_AT_BIRTH FLOAT(4),

	-- BIRTH_DEATH_GROWTH_RATES --
	CRUDE_BIRTH_RATE FLOAT(2),
	CRUDE_DEATH_RATE FLOAT(2),
	NET_MIGRATION FLOAT(2),
	NET_NATURAL_INCREASE FLOAT(3),
	GROWTH_RATE FLOAT(3),

	-- MIDYEAR_POPULATION --
	MIDYEAR_POPULATION INTEGER,

	-- MIDYEAR_POPULATION_AGE_SEX --
	SEX VARCHAR(10),
	MAX_AGE INTEGER,
	POPULATION_AGE_0 INTEGER,
	POPULATION_AGE_1 INTEGER,
	POPULATION_AGE_2 INTEGER,
	POPULATION_AGE_3 INTEGER,
	POPULATION_AGE_4 INTEGER,
	POPULATION_AGE_5 INTEGER,
	POPULATION_AGE_6 INTEGER,
	POPULATION_AGE_7 INTEGER,
	POPULATION_AGE_8 INTEGER,
	POPULATION_AGE_9 INTEGER,
	POPULATION_AGE_10 INTEGER,
	POPULATION_AGE_11 INTEGER,
	POPULATION_AGE_12 INTEGER,
	POPULATION_AGE_13 INTEGER,
	POPULATION_AGE_14 INTEGER,
	POPULATION_AGE_15 INTEGER,
	POPULATION_AGE_16 INTEGER,
	POPULATION_AGE_17 INTEGER,
	POPULATION_AGE_18 INTEGER,
	POPULATION_AGE_19 INTEGER,
	POPULATION_AGE_20 INTEGER,
	POPULATION_AGE_21 INTEGER,
	POPULATION_AGE_22 INTEGER,
	POPULATION_AGE_23 INTEGER,
	POPULATION_AGE_24 INTEGER,
	POPULATION_AGE_25 INTEGER,
	POPULATION_AGE_26 INTEGER,
	POPULATION_AGE_27 INTEGER,
	POPULATION_AGE_28 INTEGER,
	POPULATION_AGE_29 INTEGER,
	POPULATION_AGE_30 INTEGER,
	POPULATION_AGE_31 INTEGER,
	POPULATION_AGE_32 INTEGER,
	POPULATION_AGE_33 INTEGER,
	POPULATION_AGE_34 INTEGER,
	POPULATION_AGE_35 INTEGER,
	POPULATION_AGE_36 INTEGER,
	POPULATION_AGE_37 INTEGER,
	POPULATION_AGE_38 INTEGER,
	POPULATION_AGE_39 INTEGER,
	POPULATION_AGE_40 INTEGER,
	POPULATION_AGE_41 INTEGER,
	POPULATION_AGE_42 INTEGER,
	POPULATION_AGE_43 INTEGER,
	POPULATION_AGE_44 INTEGER,
	POPULATION_AGE_45 INTEGER,
	POPULATION_AGE_46 INTEGER,
	POPULATION_AGE_47 INTEGER,
	POPULATION_AGE_48 INTEGER,
	POPULATION_AGE_49 INTEGER,
	POPULATION_AGE_50 INTEGER,
	POPULATION_AGE_51 INTEGER,
	POPULATION_AGE_52 INTEGER,
	POPULATION_AGE_53 INTEGER,
	POPULATION_AGE_54 INTEGER,
	POPULATION_AGE_55 INTEGER,
	POPULATION_AGE_56 INTEGER,
	POPULATION_AGE_57 INTEGER,
	POPULATION_AGE_58 INTEGER,
	POPULATION_AGE_59 INTEGER,
	POPULATION_AGE_60 INTEGER,
	POPULATION_AGE_61 INTEGER,
	POPULATION_AGE_62 INTEGER,
	POPULATION_AGE_63 INTEGER,
	POPULATION_AGE_64 INTEGER,
	POPULATION_AGE_65 INTEGER,
	POPULATION_AGE_66 INTEGER,
	POPULATION_AGE_67 INTEGER,
	POPULATION_AGE_68 INTEGER,
	POPULATION_AGE_69 INTEGER,
	POPULATION_AGE_70 INTEGER,
	POPULATION_AGE_71 INTEGER,
	POPULATION_AGE_72 INTEGER,
	POPULATION_AGE_73 INTEGER,
	POPULATION_AGE_74 INTEGER,
	POPULATION_AGE_75 INTEGER,
	POPULATION_AGE_76 INTEGER,
	POPULATION_AGE_77 INTEGER,
	POPULATION_AGE_78 INTEGER,
	POPULATION_AGE_79 INTEGER,
	POPULATION_AGE_80 INTEGER,
	POPULATION_AGE_81 INTEGER,
	POPULATION_AGE_82 INTEGER,
	POPULATION_AGE_83 INTEGER,
	POPULATION_AGE_84 INTEGER,
	POPULATION_AGE_85 INTEGER,
	POPULATION_AGE_86 INTEGER,
	POPULATION_AGE_87 INTEGER,
	POPULATION_AGE_88 INTEGER,
	POPULATION_AGE_89 INTEGER,
	POPULATION_AGE_90 INTEGER,
	POPULATION_AGE_91 INTEGER,
	POPULATION_AGE_92 INTEGER,
	POPULATION_AGE_93 INTEGER,
	POPULATION_AGE_94 INTEGER,
	POPULATION_AGE_95 INTEGER,
	POPULATION_AGE_96 INTEGER,
	POPULATION_AGE_97 INTEGER,
	POPULATION_AGE_98 INTEGER,
	POPULATION_AGE_99 INTEGER,
	POPULATION_AGE_100 INTEGER,

	-- MORTALITY_LIFE_EXPECTANCY --
	INFANT_MORTALITY FLOAT(2),
	INFANT_MORTALITY_MALE FLOAT(2),
	INFANT_MORTALITY_FEMALE FLOAT(2),
	LIFE_EXPECTANCY FLOAT(2),
	LIFE_EXPECTANCY_MALE FLOAT(2),
	LIFE_EXPECTANCY_FEMALE FLOAT(2),
	MORTALITY_RATE_UNDER_5 FLOAT(2),
	MORTALITY_RATE_UNDER_5_MALE FLOAT(2),
	MORTALITY_RATE_UNDER_5_FEMALE FLOAT(2),
	MORTALITY_RATE_1TO4 FLOAT(2),
	MORTALITY_RATE_1TO4_MALE FLOAT(2),
	MORTALITY_RATE_1TO4_FEMALE FLOAT(2),
	FOREIGN KEY (D_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(D_COUNTRY_ID, D_YEAR)
);


-- TABLE INCOME_BY_COUNTRY --
-- Income_by_country.csv --

CREATE TABLE INCOME_BY_COUNTRY(

	-- COMMON FOR EVERY SHEET --
	I_COUNTRY_ID INTEGER NOT NULL,
	I_YEAR INTEGER NOT NULL,

	INCOME_INDEX FLOAT(3),
	LABOUR_SHARE_OF_GDP FLOAT(1),
	GROSS_FIXED_CAPITAL_FORMATION FLOAT(3),	-- 5 YEAR MEASUREMENTS --
	GDP_TOTAL FLOAT(1),
	GDP_PER_CAPITA INTEGER,
	GNI_PER_CAPITA INTEGER,
	ESTIMATED_GNI_MALE INTEGER,	-- 5 YEAR IN SOME CASES --
	ESTIMATED_GNI_FEMALE INTEGER,	-- 5 YEAR IN SOME CASES --
	DOMESTIC_CREDITS FLOAT(3), -- 5 YEAR MEASUREMENTS --
	FOREIGN KEY(I_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(I_COUNTRY_ID, I_YEAR)
);


-- INSERT DATA --
-- INSERT INTO COUNTRY(COUNTRY_ID, OFFICIAL_NAME) VALUES (43, 'GREECE');
-- INSERT INTO INCOME_BY_COUNTRY VALUES (43, 1990, 3.98, 4.5, 4.567, 23.9, 43567, 8743, 90876, 67346, 7.950);
-- INSERT INTO INTERNATIONAL_DATA(D_COUNTRY_ID, D_YEAR, COUNTRY_NAME, POPULATION_AGE_15, POPULATION_AGE_98) VALUES (43, 2008, 'GREECE', 546923, 8675);
