CREATE DATABASE IF NOT EXISTS country_data;
USE country_data;

-- SECURITY --
DROP TABLE IF EXISTS DOMESTIC_CREDS;
DROP TABLE IF EXISTS EST_GNI_F;
DROP TABLE IF EXISTS EST_GNI_M;
DROP TABLE IF EXISTS GNI_PER_CAPITA;
DROP TABLE IF EXISTS GDP_PER_CAPITA;
DROP TABLE IF EXISTS GFCF;
DROP TABLE IF EXISTS LSHGPD;
DROP TABLE IF EXISTS INCOME_INDEX;
DROP TABLE IF EXISTS MORTALITY_LIFE_EXPECTANCY;
DROP TABLE IF EXISTS MIDYEAR_POPULATION_AGE_SEX;
DROP TABLE IF EXISTS MIDYEAR_POPULATION;
DROP TABLE IF EXISTS BIRTH_DEATH_GROWTH_RATES;
DROP TABLE IF EXISTS AGE_SPECIFIC_FERTILITY_RATES;
DROP TABLE IF EXISTS COUNTRY;



-- TABLE COUNTRY --
-- countries.csv and country_names_area.csv --

CREATE TABLE COUNTRY (
	COUNTRY_ID INTEGER NOT NULL,
	ISO VARCHAR(2),
	ISO3 VARCHAR(3),
	FIPS VARCHAR(2),
	DISPLAY_NAME VARCHAR(20),
	OFFICIAL_NAME VARCHAR(20),
	CAPITAL VARCHAR(20),
	COUNTRY_AREA FLOAT(2),
	CONTINENT VARCHAR(20),
	CURRENCY_CODE VARCHAR(3),
	CURRENCY_NAME VARCHAR(20),
	PHONE INTEGER,
	REGION_CODE INTEGER,
	REGION_NAME VARCHAR(20),
	SUBREGION_CODE INTEGER,
	SUBREGION_NAME VARCHAR(20),
	INTERMEDIATE_REGION_CODE INTEGER,
	INTERMEDIATE_REGION_NAME VARCHAR(20),
	C_STATUS VARCHAR(20),
	DEVELOPMENT VARCHAR(20),
	SIDS BOOLEAN,	-- SMALL ISLAND DEVELOPING STATES
	LLDC BOOLEAN,	-- LAND LOCKED DEVELOPING COUNTRIES
	LDC BOOLEAN,	-- LEAST DEVELOPED COUNTRIES
	AREA_SQKM INTEGER,
	POPULATION INTEGER,
	PRIMARY KEY(COUNTRY_ID)
);

-- TABLE AGE_SPECIFIC_FERTILITY_RATES --
CREATE TABLE AGE_SPECIFIC_FERTILITY_RATES (
    FR_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	FR_YEAR INTEGER UNIQUE NOT NULL,
	COUNTRY_NAME VARCHAR(20),
    FERTILITY_RATE_15_19 FLOAT(1),
	FERTILITY_RATE_20_24 FLOAT(1),
	FERTILITY_RATE_25_29 FLOAT(1),
	FERTILITY_RATE_30_34 FLOAT(1),
	FERTILITY_RATE_35_39 FLOAT(1),
	FERTILITY_RATE_40_44 FLOAT(1),
	FERTILITY_RATE_45_49 FLOAT(1),
	TOTAL_FERTILITY_RATE FLOAT(4),
	GROSS_REPRODUCTION_RATE FLOAT(4),
	SEX_RATIO_AT_BIRTH FLOAT(4),
    FOREIGN KEY (FR_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(FR_COUNTRY_ID, FR_YEAR)
);

-- TABLE BIRTH_DEATH_GROWTH_RATES --
CREATE TABLE BIRTH_DEATH_GROWTH_RATES(
    BD_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	BD_YEAR INTEGER UNIQUE NOT NULL,
	COUNTRY_NAME VARCHAR(20),
	CRUDE_BIRTH_RATE FLOAT(2),
	CRUDE_DEATH_RATE FLOAT(2),
	NET_MIGRATION FLOAT(2),
	NET_NATURAL_INCREASE FLOAT(3),
	GROWTH_RATE FLOAT(3),
    FOREIGN KEY (BD_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(BD_COUNTRY_ID, BD_YEAR)
);

-- TABLE MIDYEAR_POPULATION --
CREATE TABLE MIDYEAR_POPULATION(
    P_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	P_YEAR INTEGER UNIQUE NOT NULL,
	COUNTRY_NAME VARCHAR(20),
	MIDYEAR_POPULATION_ INTEGER,
    FOREIGN KEY (P_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(P_COUNTRY_ID, P_YEAR)
);

-- TABLE MIDYEAR_POPULATION_AGE_SEX --
CREATE TABLE MIDYEAR_POPULATION_AGE_SEX(
    PAS_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	PAS_YEAR INTEGER UNIQUE NOT NULL,
	COUNTRY_NAME VARCHAR(20),
	SEX VARCHAR(10),
	MAX_AGE INTEGER,
	POPULATION_AGE_0 INTEGER,
	POPULATION_AGE_1 INTEGER,
	POPULATION_AGE_2 INTEGER,
	POPULATION_AGE_3 INTEGER,
	POPULATION_AGE_4 INTEGER,
	POPULATION_AGE_5 INTEGER,
	POPULATION_AGE_6 INTEGER,
	POPULATION_AGE_7 INTEGER,
	POPULATION_AGE_8 INTEGER,
	POPULATION_AGE_9 INTEGER,
	POPULATION_AGE_10 INTEGER,
	POPULATION_AGE_11 INTEGER,
	POPULATION_AGE_12 INTEGER,
	POPULATION_AGE_13 INTEGER,
	POPULATION_AGE_14 INTEGER,
	POPULATION_AGE_15 INTEGER,
	POPULATION_AGE_16 INTEGER,
	POPULATION_AGE_17 INTEGER,
	POPULATION_AGE_18 INTEGER,
	POPULATION_AGE_19 INTEGER,
	POPULATION_AGE_20 INTEGER,
	POPULATION_AGE_21 INTEGER,
	POPULATION_AGE_22 INTEGER,
	POPULATION_AGE_23 INTEGER,
	POPULATION_AGE_24 INTEGER,
	POPULATION_AGE_25 INTEGER,
	POPULATION_AGE_26 INTEGER,
	POPULATION_AGE_27 INTEGER,
	POPULATION_AGE_28 INTEGER,
	POPULATION_AGE_29 INTEGER,
	POPULATION_AGE_30 INTEGER,
	POPULATION_AGE_31 INTEGER,
	POPULATION_AGE_32 INTEGER,
	POPULATION_AGE_33 INTEGER,
	POPULATION_AGE_34 INTEGER,
	POPULATION_AGE_35 INTEGER,
	POPULATION_AGE_36 INTEGER,
	POPULATION_AGE_37 INTEGER,
	POPULATION_AGE_38 INTEGER,
	POPULATION_AGE_39 INTEGER,
	POPULATION_AGE_40 INTEGER,
	POPULATION_AGE_41 INTEGER,
	POPULATION_AGE_42 INTEGER,
	POPULATION_AGE_43 INTEGER,
	POPULATION_AGE_44 INTEGER,
	POPULATION_AGE_45 INTEGER,
	POPULATION_AGE_46 INTEGER,
	POPULATION_AGE_47 INTEGER,
	POPULATION_AGE_48 INTEGER,
	POPULATION_AGE_49 INTEGER,
	POPULATION_AGE_50 INTEGER,
	POPULATION_AGE_51 INTEGER,
	POPULATION_AGE_52 INTEGER,
	POPULATION_AGE_53 INTEGER,
	POPULATION_AGE_54 INTEGER,
	POPULATION_AGE_55 INTEGER,
	POPULATION_AGE_56 INTEGER,
	POPULATION_AGE_57 INTEGER,
	POPULATION_AGE_58 INTEGER,
	POPULATION_AGE_59 INTEGER,
	POPULATION_AGE_60 INTEGER,
	POPULATION_AGE_61 INTEGER,
	POPULATION_AGE_62 INTEGER,
	POPULATION_AGE_63 INTEGER,
	POPULATION_AGE_64 INTEGER,
	POPULATION_AGE_65 INTEGER,
	POPULATION_AGE_66 INTEGER,
	POPULATION_AGE_67 INTEGER,
	POPULATION_AGE_68 INTEGER,
	POPULATION_AGE_69 INTEGER,
	POPULATION_AGE_70 INTEGER,
	POPULATION_AGE_71 INTEGER,
	POPULATION_AGE_72 INTEGER,
	POPULATION_AGE_73 INTEGER,
	POPULATION_AGE_74 INTEGER,
	POPULATION_AGE_75 INTEGER,
	POPULATION_AGE_76 INTEGER,
	POPULATION_AGE_77 INTEGER,
	POPULATION_AGE_78 INTEGER,
	POPULATION_AGE_79 INTEGER,
	POPULATION_AGE_80 INTEGER,
	POPULATION_AGE_81 INTEGER,
	POPULATION_AGE_82 INTEGER,
	POPULATION_AGE_83 INTEGER,
	POPULATION_AGE_84 INTEGER,
	POPULATION_AGE_85 INTEGER,
	POPULATION_AGE_86 INTEGER,
	POPULATION_AGE_87 INTEGER,
	POPULATION_AGE_88 INTEGER,
	POPULATION_AGE_89 INTEGER,
	POPULATION_AGE_90 INTEGER,
	POPULATION_AGE_91 INTEGER,
	POPULATION_AGE_92 INTEGER,
	POPULATION_AGE_93 INTEGER,
	POPULATION_AGE_94 INTEGER,
	POPULATION_AGE_95 INTEGER,
	POPULATION_AGE_96 INTEGER,
	POPULATION_AGE_97 INTEGER,
	POPULATION_AGE_98 INTEGER,
	POPULATION_AGE_99 INTEGER,
	POPULATION_AGE_100 INTEGER,
    FOREIGN KEY (PAS_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(PAS_COUNTRY_ID, PAS_YEAR)
);

-- TABLE MORTALITY_LIFE_EXPECTANCY --
CREATE TABLE MORTALITY_LIFE_EXPECTANCY(
    M_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	M_YEAR INTEGER UNIQUE NOT NULL,
	COUNTRY_NAME VARCHAR(20),
	INFANT_MORTALITY FLOAT(2),
	INFANT_MORTALITY_MALE FLOAT(2),
	INFANT_MORTALITY_FEMALE FLOAT(2),
	LIFE_EXPECTANCY FLOAT(2),
	LIFE_EXPECTANCY_MALE FLOAT(2),
	LIFE_EXPECTANCY_FEMALE FLOAT(2),
	MORTALITY_RATE_UNDER_5 FLOAT(2),
	MORTALITY_RATE_UNDER_5_MALE FLOAT(2),
	MORTALITY_RATE_UNDER_5_FEMALE FLOAT(2),
	MORTALITY_RATE_1TO4 FLOAT(2),
	MORTALITY_RATE_1TO4_MALE FLOAT(2),
	MORTALITY_RATE_1TO4_FEMALE FLOAT(2),
	FOREIGN KEY (M_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(M_COUNTRY_ID, M_YEAR)
);

-- TABLES FOR INCOME_BY_COUNTRY --
-- Income_by_country.csv --

CREATE TABLE INCOME_INDEX(
	I_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	I_YEAR INTEGER UNIQUE NOT NULL,
	INCOME_INDEX_ FLOAT(3),
    FOREIGN KEY(I_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(I_COUNTRY_ID, I_YEAR)
);

CREATE TABLE LSHGPD(
	L_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	L_YEAR INTEGER UNIQUE NOT NULL,
	LABOUR_SHARE_OF_GDP FLOAT(1),
	FOREIGN KEY(L_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(L_COUNTRY_ID, L_YEAR)
);

CREATE TABLE GFCF(
	GFCF_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	GFCF_YEAR INTEGER UNIQUE NOT NULL,
	GROSS_FIXED_CAPITAL_FORMATION FLOAT(3),	-- 5 YEAR MEASUREMENTS --
	FOREIGN KEY(GFCF_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(GFCF_COUNTRY_ID, GFCF_YEAR)
);

CREATE TABLE TOTAL_GPD(
	GPD_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	GPD_YEAR INTEGER UNIQUE NOT NULL,
	GDP_TOTAL FLOAT(1),
	FOREIGN KEY(GPD_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(GPD_COUNTRY_ID, GPD_YEAR)
);


CREATE TABLE GDP_PER_CAPITA(
	GPDC_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	GPDC_YEAR INTEGER UNIQUE NOT NULL,
	GDP_PER_CAPITA_ INTEGER,
	FOREIGN KEY(GPDC_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(GPDC_COUNTRY_ID, GPDC_YEAR)
);

CREATE TABLE GNI_PER_CAPITA(
	GNI_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	GNI_YEAR INTEGER UNIQUE NOT NULL,
	GNI_PER_CAPITA_ INTEGER,
	FOREIGN KEY(GNI_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(GNI_COUNTRY_ID, GNI_YEAR)
);

CREATE TABLE EST_GNI_M(
	GNIM_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	GNIM_YEAR INTEGER UNIQUE NOT NULL,
	ESTIMATED_GNI_MALE INTEGER,	-- 5 YEAR IN SOME CASES --
	FOREIGN KEY(GNIM_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(GNIM_COUNTRY_ID, GNIM_YEAR)
);

CREATE TABLE EST_GNI_F(
	GNIF_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	GNIF_YEAR INTEGER UNIQUE NOT NULL,
	ESTIMATED_GNI_FEMALE INTEGER,	-- 5 YEAR IN SOME CASES --
	FOREIGN KEY(GNIF_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(GNIF_COUNTRY_ID, GNIF_YEAR)
);

CREATE TABLE DOMESTIC_CREDS(
	DC_COUNTRY_ID INTEGER UNIQUE NOT NULL,
	DC_YEAR INTEGER UNIQUE NOT NULL,
	DOMESTIC_CREDITS FLOAT(3), -- 5 YEAR MEASUREMENTS --
	FOREIGN KEY(DC_COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
	PRIMARY KEY(DC_COUNTRY_ID, DC_YEAR)
);
